### ISSUE TITLE
No such file or director

### ISSUE THREAD

**Issue by chadwcarlson** [platformsh-templates/wordpress-vanilla#12]
Running the template through template-builder (full) via the scheduled workflow results in the failed build. 

```
 Found 12 commits
 
 Building application 'app' (runtime type: php:8.1, tree: 7fea54d)
   Generating runtime configuration.
   
   Installing build dependencies...
     Installing php build dependencies: wp-cli/wp-cli-bundle, psy/psysh
     W: PHP Deprecated:  Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/vendor/symfony/console/Helper/HelperSet.php on line 112
     
     Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/vendor/symfony/console/Helper/HelperSet.php on line 112
     W: Changed current directory to /app/.global/wp-cli/wp-cli-bundle
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:66
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:67
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:69
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:71
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:66
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:67
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:69
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:71
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:66
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:66
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:67
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:69
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:71
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:66
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:67
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:69
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:71
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:66
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:67
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:69
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:71
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:66
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:67
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:69
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:71
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:66
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:67
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:69
     W: Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in phar:///usr/bin/composer/vendor/symfony/console/Input/StringInput.php:71
     W: Deprecation Notice: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php:48
     W: Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/src/Composer/Repository/ArrayRepository.php:206
     W: Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/src/Composer/Repository/ArrayRepository.php:206
     W: Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/src/Composer/Repository/ArrayRepository.php:206
     W: Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/src/Composer/Repository/ArrayRepository.php:206
     W: Deprecation Notice: Return type of Composer\Repository\CompositeRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/src/Composer/Repository/CompositeRepository.php:139
     W: Loading composer repositories with package information
     W: Deprecation Notice: Return type of Composer\DependencyResolver\Pool::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/src/Composer/DependencyResolver/Pool.php:175
     W: Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/
     W: Updating dependencies (including require-dev)
     W: Deprecation Notice: Return type of Composer\DependencyResolver\RuleSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/src/Composer/DependencyResolver/RuleSet.php:114
     W: Deprecation Notice: Return type of Composer\DependencyResolver\RuleSet::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/src/Composer/DependencyResolver/RuleSet.php:99
     W: Deprecation Notice: Return type of Composer\DependencyResolver\Decisions::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/src/Composer/DependencyResolver/Decisions.php:155
     W: Deprecation Notice: Return type of Composer\DependencyResolver\Decisions::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/src/Composer/DependencyResolver/Decisions.php:165
     W: Deprecation Notice: Return type of Composer\DependencyResolver\Decisions::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/src/Composer/DependencyResolver/Decisions.php:160
     W: Deprecation Notice: Return type of Composer\DependencyResolver\Decisions::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/src/Composer/DependencyResolver/Decisions.php:170
     W: Deprecation Notice: Return type of Composer\DependencyResolver\Decisions::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/src/Composer/DependencyResolver/Decisions.php:150
     W: Deprecation Notice: Return type of Composer\DependencyResolver\Decisions::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/src/Composer/DependencyResolver/Decisions.php:145
     W: Deprecation Notice: Return type of Composer\DependencyResolver\RuleSetIterator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/src/Composer/DependencyResolver/RuleSetIterator.php:36
     W: Deprecation Notice: Return type of Composer\DependencyResolver\RuleSetIterator::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/src/Composer/DependencyResolver/RuleSetIterator.php:46
     W: Deprecation Notice: Return type of Composer\DependencyResolver\RuleSetIterator::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/src/Composer/DependencyResolver/RuleSetIterator.php:41
     W: Deprecation Notice: Return type of Composer\DependencyResolver\RuleSetIterator::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/src/Composer/DependencyResolver/RuleSetIterator.php:89
     W: Deprecation Notice: Return type of Composer\DependencyResolver\RuleSetIterator::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/src/Composer/DependencyResolver/RuleSetIterator.php:70
     W: Package operations: 62 installs, 0 updates, 0 removals
     W:   - Installing wp-cli/php-cli-tools (v0.11.13): Deprecation Notice: Return type of Symfony\Component\Finder\Finder::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/vendor/symfony/finder/Finder.php:675
     W: Deprecation Notice: Return type of Symfony\Component\Finder\Finder::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/vendor/symfony/finder/Finder.php:732
     W: Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::getChildren() should either be compatible with RecursiveDirectoryIterator::getChildren(): RecursiveDirectoryIterator, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:85
     W: Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::rewind() should either be compatible with FilesystemIterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:113
     W: Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::current() should either be compatible with FilesystemIterator::current(): SplFileInfo|FilesystemIterator|string, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:65
     W: Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\FilterIterator::rewind() should either be compatible with FilterIterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/vendor/symfony/finder/Iterator/FilterIterator.php:30
     W: Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\DepthRangeFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/vendor/symfony/finder/Iterator/DepthRangeFilterIterator.php:41
     W: Loading from cache
     W: Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\FilenameFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/vendor/symfony/finder/Iterator/FilenameFilterIterator.php:28
     W:   - Installing wp-cli/mustangostang-spyc (0.6.3): Loading from cache
     W:   - Installing symfony/finder (v6.0.3): Downloading (100%)
     W:   - Installing symfony/polyfill-php80 (v1.24.0): Loading from cache
     W:   - Installing symfony/deprecation-contracts (v3.0.0): Downloading (100%)
     W:   - Installing rmccue/requests (v1.8.1): Loading from cache
     W:   - Installing mustache/mustache (v2.14.1): Loading from cache
     W:   - Installing wp-cli/wp-cli (v2.6.0): Loading from cache
     W:   - Installing wp-cli/widget-command (v2.1.7): Loading from cache
     W:   - Installing wp-cli/super-admin-command (v2.0.10): Loading from cache
     W:   - Installing wp-cli/shell-command (v2.0.11): Loading from cache
     W:   - Installing wp-cli/server-command (v2.0.10): Loading from cache
     W:   - Installing wp-cli/search-replace-command (v2.0.16): Loading from cache
     W:   - Installing wp-cli/scaffold-command (v2.0.16): Loading from cache
     W:   - Installing wp-cli/role-command (v2.0.9): Loading from cache
     W:   - Installing wp-cli/rewrite-command (v2.0.10): Loading from cache
     W:   - Installing composer/pcre (1.0.1): Loading from cache
     W:   - Installing react/promise (v2.9.0): Loading from cache
     W:   - Installing symfony/process (v6.0.3): Downloading (100%)
     W:   - Installing symfony/polyfill-mbstring (v1.24.0): Loading from cache
     W:   - Installing symfony/polyfill-ctype (v1.24.0): Loading from cache
     W:   - Installing symfony/filesystem (v6.0.3): Downloading (100%)
     W:   - Installing symfony/polyfill-intl-normalizer (v1.24.0): Loading from cache
     W:   - Installing symfony/polyfill-intl-grapheme (v1.24.0): Loading from cache
     W:   - Installing symfony/string (v6.0.3): Downloading (100%)
     W:   - Installing psr/container (2.0.2): Downloading (100%)
     W:   - Installing symfony/service-contracts (v3.0.0): Downloading (100%)
     W:   - Installing symfony/polyfill-php73 (v1.24.0): Loading from cache
     W:   - Installing symfony/console (v5.4.3): Loading from cache
     W:   - Installing psr/log (2.0.0): Downloading (100%)
     W:   - Installing seld/phar-utils (1.2.0): Loading from cache
     W:   - Installing seld/jsonlint (1.8.3): Loading from cache
     W:   - Installing justinrainbow/json-schema (5.2.11): Loading from cache
     W:   - Installing composer/xdebug-handler (2.0.4): Loading from cache
     W:   - Installing composer/spdx-licenses (1.5.6): Loading from cache
     W:   - Installing composer/semver (3.2.9): Loading from cache
     W:   - Installing composer/metadata-minifier (1.0.0): Loading from cache
     W:   - Installing composer/ca-bundle (1.3.1): Loading from cache
     W:   - Installing composer/composer (2.2.6): Loading from cache
     W:   - Installing wp-cli/package-command (v2.2.2): Loading from cache
     W:   - Installing wp-cli/media-command (v2.0.12): Loading from cache
     W:   - Installing wp-cli/maintenance-mode-command (v2.0.8): Loading from cache
     W:   - Installing wp-cli/language-command (v2.0.12): Loading from cache
     W:   - Installing wp-cli/import-command (v2.0.8): Loading from cache
     W:   - Installing mck89/peast (v1.13.11): Loading from cache
     W:   - Installing gettext/languages (2.9.0): Loading from cache
     W:   - Installing gettext/gettext (v4.8.6): Loading from cache
     W:   - Installing wp-cli/i18n-command (v2.2.13): Loading from cache
     W:   - Installing wp-cli/extension-command (v2.1.4): Loading from cache
     W:   - Installing nb/oxymel (v0.1.0): Loading from cache
     W:   - Installing wp-cli/export-command (v2.0.11): Loading from cache
     W:   - Installing wp-cli/eval-command (v2.1.2): Loading from cache
     W:   - Installing wp-cli/entity-command (v2.2.1): Loading from cache
     W:   - Installing wp-cli/embed-command (v2.0.11): Loading from cache
     W:   - Installing wp-cli/db-command (v2.0.20): Loading from cache
     W:   - Installing wp-cli/cron-command (v2.1.0): Loading from cache
     W:   - Installing wp-cli/core-command (v2.1.1): Loading from cache
     W:   - Installing wp-cli/wp-config-transformer (v1.3.0): Loading from cache
     W:   - Installing wp-cli/config-command (v2.1.3): Loading from cache
     W:   - Installing wp-cli/checksum-command (v2.1.2): Loading from cache
     W:   - Installing wp-cli/cache-command (v2.0.9): Loading from cache
     W:   - Installing wp-cli/wp-cli-bundle (v2.6.0): Loading from cache
     W: wp-cli/wp-cli suggests installing ext-readline (Include for a better --prompt implementation)
     W: symfony/service-contracts suggests installing symfony/service-implementation
     W: symfony/console suggests installing symfony/event-dispatcher
     W: symfony/console suggests installing symfony/lock
     W: gettext/gettext suggests installing illuminate/view (Is necessary if you want to use the Blade extractor)
     W: gettext/gettext suggests installing twig/twig (Is necessary if you want to use the Twig extractor)
     W: gettext/gettext suggests installing twig/extensions (Is necessary if you want to use the Twig extractor)
     W: gettext/gettext suggests installing symfony/yaml (Is necessary if you want to use the Yaml extractor/generator)
     W: wp-cli/wp-cli-bundle suggests installing psy/psysh (Enhanced `wp shell` functionality)
     W: Writing lock file
     W: Generating optimized autoload files
     W: Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\FileTypeFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/vendor/symfony/finder/Iterator/FileTypeFilterIterator.php:42
     W: Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php:55
     W: Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::hasChildren() should either be compatible with RecursiveIterator::hasChildren(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php:71
     W: Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::getChildren() should either be compatible with RecursiveIterator::getChildren(): ?RecursiveIterator, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php:76
     W: Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\FilterIterator::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/vendor/symfony/finder/Iterator/FilterIterator.php:30
     W: Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\PathFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/composer/vendor/symfony/finder/Iterator/PathFilterIterator.php:27
     W: 24 packages you are using are looking for funding.
     W: Use the `composer fund` command to find out more!
     W: Changed current directory to /app/.global/psy/psysh
     W: No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
     W: Loading composer repositories with package information
     W: Updating dependencies
     W: Lock file operations: 14 installs, 0 updates, 0 removals
     W:   - Locking nikic/php-parser (v4.13.2)
     W:   - Locking psr/container (2.0.2)
     W:   - Locking psy/psysh (v0.10.12)
     W:   - Locking symfony/console (v5.4.3)
     W:   - Locking symfony/deprecation-contracts (v3.0.0)
     W:   - Locking symfony/polyfill-ctype (v1.24.0)
     W:   - Locking symfony/polyfill-intl-grapheme (v1.24.0)
     W:   - Locking symfony/polyfill-intl-normalizer (v1.24.0)
     W:   - Locking symfony/polyfill-mbstring (v1.24.0)
     W:   - Locking symfony/polyfill-php73 (v1.24.0)
     W:   - Locking symfony/polyfill-php80 (v1.24.0)
     W:   - Locking symfony/service-contracts (v3.0.0)
     W:   - Locking symfony/string (v6.0.3)
     W:   - Locking symfony/var-dumper (v5.4.3)
     W: Writing lock file
     W: Installing dependencies from lock file (including require-dev)
     W: Package operations: 3 installs, 0 updates, 51 removals
     W:   - Removing wp-cli/wp-config-transformer (v1.3.0)
     W:   - Removing wp-cli/wp-cli-bundle (v2.6.0)
     W:   - Removing wp-cli/wp-cli (v2.6.0)
     W:   - Removing wp-cli/widget-command (v2.1.7)
     W:   - Removing wp-cli/super-admin-command (v2.0.10)
     W:   - Removing wp-cli/shell-command (v2.0.11)
     W:   - Removing wp-cli/server-command (v2.0.10)
     W:   - Removing wp-cli/search-replace-command (v2.0.16)
     W:   - Removing wp-cli/scaffold-command (v2.0.16)
     W:   - Removing wp-cli/role-command (v2.0.9)
     W:   - Removing wp-cli/rewrite-command (v2.0.10)
     W:   - Removing wp-cli/php-cli-tools (v0.11.13)
     W:   - Removing wp-cli/package-command (v2.2.2)
     W:   - Removing wp-cli/mustangostang-spyc (0.6.3)
     W:   - Removing wp-cli/media-command (v2.0.12)
     W:   - Removing wp-cli/maintenance-mode-command (v2.0.8)
     W:   - Removing wp-cli/language-command (v2.0.12)
     W:   - Removing wp-cli/import-command (v2.0.8)
     W:   - Removing wp-cli/i18n-command (v2.2.13)
     W:   - Removing wp-cli/extension-command (v2.1.4)
     W:   - Removing wp-cli/export-command (v2.0.11)
     W:   - Removing wp-cli/eval-command (v2.1.2)
     W:   - Removing wp-cli/entity-command (v2.2.1)
     W:   - Removing wp-cli/embed-command (v2.0.11)
     W:   - Removing wp-cli/db-command (v2.0.20)
     W:   - Removing wp-cli/cron-command (v2.1.0)
     W:   - Removing wp-cli/core-command (v2.1.1)
     W:   - Removing wp-cli/config-command (v2.1.3)
     W:   - Removing wp-cli/checksum-command (v2.1.2)
     W:   - Removing wp-cli/cache-command (v2.0.9)
     W:   - Removing symfony/process (v6.0.3)
     W:   - Removing symfony/finder (v6.0.3)
     W:   - Removing symfony/filesystem (v6.0.3)
     W:   - Removing seld/phar-utils (1.2.0)
     W:   - Removing seld/jsonlint (1.8.3)
     W:   - Removing rmccue/requests (v1.8.1)
     W:   - Removing react/promise (v2.9.0)
     W:   - Removing psr/log (2.0.0)
     W:   - Removing nb/oxymel (v0.1.0)
     W:   - Removing mustache/mustache (v2.14.1)
     W:   - Removing mck89/peast (v1.13.11)
     W:   - Removing justinrainbow/json-schema (5.2.11)
     W:   - Removing gettext/languages (2.9.0)
     W:   - Removing gettext/gettext (v4.8.6)
     W:   - Removing composer/xdebug-handler (2.0.4)
     W:   - Removing composer/spdx-licenses (1.5.6)
     W:   - Removing composer/semver (3.2.9)
     W:   - Removing composer/pcre (1.0.1)
     W:   - Removing composer/metadata-minifier (1.0.0)
     W:   - Removing composer/composer (2.2.6)
     W:   - Removing composer/ca-bundle (1.3.1)
     W:   - Installing symfony/var-dumper (v5.4.3): Extracting archive
     W:   - Installing nikic/php-parser (v4.13.2): Extracting archive
     W:   - Installing psy/psysh (v0.10.12): Extracting archive
     W: 
     W: In ClassLoader.php line 444:
     W:                                                                                
     W:   include(/app/.global/vendor/composer/../composer/composer/src/Composer/Cons  
     W:   ole/GithubActionError.php): Failed to open stream: No such file or director  
     W:   y                                                                            
     W:                                                                                
     W: 
     W: install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]
     W: 
   
   E: Error building project: `composer` could not be run.
 
 E: Error: Unable to build application, aborting.
 
```
